import { useState } from 'react'
import { FileSpreadsheet, PackageCheck, Plus, X } from 'lucide-react'
import materialSeed from '../data/materials.json'

const empty={itemNumber:'',description:'',category:'',unit:'EA',storeroom:'DIWAN-MAIN',balance:0,reserved:0,reorderLevel:0,availability:'Available'}
export default function MaterialsPage(){
  const [materials,setMaterials]=useState(materialSeed),[adding,setAdding]=useState(false),[form,setForm]=useState(empty),[imported,setImported]=useState('')
  const save=()=>{if(!form.itemNumber||!form.description)return;setMaterials(rows=>[...rows,{...form,balance:Number(form.balance),reserved:Number(form.reserved),reorderLevel:Number(form.reorderLevel)}]);setForm(empty);setAdding(false)}
  return <><section className="page-heading"><div><p className="eyebrow">INVENTORY MASTER DATA</p><h1>Materials</h1><p>Maintain spare parts, consumables, balances, reservations, and reorder levels.</p></div><div className="heading-actions"><label className="outline inventory-import"><FileSpreadsheet size={16}/>{imported||'Import Excel'}<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setImported(e.target.files?.[0]?.name||'')}/></label><button className="primary" onClick={()=>setAdding(true)}><Plus size={17}/>Add material</button></div></section>{imported&&<div className="inventory-import-note"><PackageCheck size={16}/><span><strong>{imported}</strong> ready for inventory validation and stock update.</span><button onClick={()=>setImported('')}><X size={14}/></button></div>}<section className="master-summary"><PackageCheck size={18}/><span>Inventory items</span><strong>{materials.length}</strong><i>Purchase required {materials.filter(item=>item.availability==='Purchase Required').length}</i></section>{adding&&<section className="panel inventory-editor"><header><div><h3>Manual inventory entry</h3><p>Add a spare part or consumable without an Excel import.</p></div><button onClick={()=>setAdding(false)}><X/></button></header><div>{[['Item Number','itemNumber'],['Description','description'],['Category','category'],['Unit','unit'],['Storeroom','storeroom'],['Balance','balance'],['Reserved','reserved'],['Reorder Level','reorderLevel']].map(([label,key])=><label key={key}><span>{label}</span><input type={['balance','reserved','reorderLevel'].includes(key)?'number':'text'} value={form[key]} onChange={e=>setForm(current=>({...current,[key]:e.target.value}))}/></label>)}</div><footer><button className="outline" onClick={()=>setAdding(false)}>Cancel</button><button className="primary" onClick={save}>Add material</button></footer></section>}<section className="panel register"><div className="table-shell"><table><thead><tr><th>Item number</th><th>Description</th><th>Category</th><th>Unit</th><th>Storeroom</th><th>Balance</th><th>Reserved</th><th>Reorder level</th><th>Availability</th></tr></thead><tbody>{materials.map(item=><tr key={item.itemNumber}><td><strong className="mono">{item.itemNumber}</strong></td><td>{item.description}</td><td>{item.category}</td><td>{item.unit}</td><td>{item.storeroom}</td><td>{item.balance}</td><td>{item.reserved}</td><td>{item.reorderLevel}</td><td><span className={`badge ${item.availability==='Available'?'green':'orange'}`}><i/>{item.availability}</span></td></tr>)}</tbody></table></div></section></>
}
